# Generated by Django 4.1.5 on 2023-04-26 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="In_img",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("input_url", models.CharField(max_length=100)),
                ("upload_by", models.IntegerField()),
                ("upload_time", models.DateTimeField(auto_now_add=True)),
                ("chosen_net", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Net",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("net_name", models.CharField(max_length=15)),
                ("description", models.TextField()),
                ("in_channel", models.IntegerField()),
                ("in_size", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Out_img",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("output_url", models.CharField(max_length=100)),
                ("corr_input", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=10)),
                ("password", models.CharField(max_length=20)),
                ("is_admin", models.BooleanField(default=False)),
                ("email", models.CharField(max_length=30, unique=True)),
                ("institution", models.CharField(max_length=20)),
                ("age", models.IntegerField(default=18)),
                ("gender", models.IntegerField(default=0)),
                ("reason", models.IntegerField(default=0)),
            ],
        ),
    ]
