# Generated by Django 4.1.5 on 2023-04-27 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="net",
            name="net_file",
            field=models.CharField(default="Swin_UNet.pth", max_length=20),
            preserve_default=False,
        ),
    ]
