# Generated by Django 4.1.5 on 2023-04-28 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_net_net_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="Record",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("input_url", models.CharField(max_length=100)),
                ("upload_time", models.DateTimeField(auto_now_add=True)),
                ("chosen_net", models.CharField(max_length=15)),
                ("output_url", models.CharField(max_length=100)),
                (
                    "upload_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.user"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(name="In_img",),
        migrations.DeleteModel(name="Out_img",),
    ]
